// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManager.Data;

#nullable disable

namespace ProjectManager.Data.Migrations
{
    [DbContext(typeof(ProjectManagerDbContext))]
    [Migration("20250507184003_AddUsersTable")]
    partial class AddUsersTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManager.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 4, 7, 13, 52, 3, 16, DateTimeKind.Utc).AddTicks(2796),
                            Description = "Aplikacja backendowa w .NET do obsługi kont użytkowników",
                            Name = "System zarządzania użytkownikami"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 4, 15, 6, 40, 3, 16, DateTimeKind.Utc).AddTicks(2810),
                            Description = "Frontendowy panel administracyjny dla systemu zarządzania użytkownikami",
                            Name = "Panel administracyjny Angular"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2025, 3, 27, 23, 28, 3, 16, DateTimeKind.Utc).AddTicks(2813),
                            Description = "Moduł płatności w .NET integrujący różne bramki płatności",
                            Name = "API do obsługi płatności"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 4, 12, 1, 52, 3, 16, DateTimeKind.Utc).AddTicks(2815),
                            Description = "Aplikacja w Angular do analizy sprzedaży i monitorowania zamówień",
                            Name = "Dashboard dla e-commerce"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 5, 5, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2816),
                            Description = "API backendowe dla aplikacji mobilnej do zarządzania zamówieniami",
                            Name = "Aplikacja mobilna dla klientów"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 5, 6, 11, 28, 3, 16, DateTimeKind.Utc).AddTicks(2820),
                            Description = "System zarządzania treścią w .NET dla blogów technologicznych",
                            Name = "CMS dla blogerów"
                        });
                });

            modelBuilder.Entity("ProjectManager.Data.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dodanie funkcji rejestracji z walidacją danych",
                            DueDate = new DateTime(2025, 4, 23, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2877),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Implementacja rejestracji użytkowników"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Funkcja resetowania hasła z kodem weryfikacyjnym na e-mail",
                            DueDate = new DateTime(2025, 4, 17, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2882),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Obsługa resetowania hasła"
                        },
                        new
                        {
                            Id = 3,
                            Description = "System ról i uprawnień dla różnych typów kont",
                            DueDate = new DateTime(2025, 4, 12, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2884),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Dodanie ról użytkowników"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Uwierzytelnianie użytkowników za pomocą tokenów JWT",
                            DueDate = new DateTime(2025, 4, 27, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2886),
                            IsCompleted = true,
                            ProjectId = 1,
                            Title = "Logowanie z wykorzystaniem JWT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Panel z listą użytkowników i ich statusem",
                            DueDate = new DateTime(2025, 4, 25, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2888),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Stworzenie dashboardu administratora"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Formularz edycji danych użytkownika",
                            DueDate = new DateTime(2025, 4, 19, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2891),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Dodanie edycji profilu użytkownika"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Blokowanie dostępu do sekcji dla nieuprawnionych użytkowników",
                            DueDate = new DateTime(2025, 4, 15, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2893),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Obsługa autoryzacji w panelu"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Dodanie obsługi płatności przez PayU",
                            DueDate = new DateTime(2025, 4, 7, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2959),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Integracja z PayU"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Obsługa powiadomień zwrotnych z bramki płatności",
                            DueDate = new DateTime(2025, 4, 2, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2961),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Implementacja webhooków dla transakcji"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Możliwość zwrotu środków użytkownikowi",
                            DueDate = new DateTime(2025, 3, 28, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2965),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Obsługa zwrotów płatności"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Wykresy i dane dotyczące sprzedaży w sklepie",
                            DueDate = new DateTime(2025, 4, 22, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2967),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Wyświetlanie statystyk sprzedaży"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Podsumowanie najczęściej kupowanych produktów",
                            DueDate = new DateTime(2025, 4, 12, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2969),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Moduł analizy trendów zakupowych"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Funkcja generowania raportów sprzedaży w formacie PDF",
                            DueDate = new DateTime(2025, 4, 17, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2971),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Eksport raportów do PDF"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Obsługa użytkowników w aplikacji mobilnej",
                            DueDate = new DateTime(2025, 5, 5, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2973),
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "API do logowania i rejestracji"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Funkcja składania zamówień w aplikacji",
                            DueDate = new DateTime(2025, 5, 6, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2974),
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Obsługa zamówień przez API"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Implementacja płatności mobilnych w aplikacji",
                            DueDate = new DateTime(2025, 5, 5, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2976),
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Obsługa płatności mobilnych"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Edytor WYSIWYG do tworzenia treści blogowych",
                            DueDate = new DateTime(2025, 5, 7, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2978),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Dodanie edytora tekstu dla blogów"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Obsługa komentarzy pod postami",
                            DueDate = new DateTime(2025, 5, 7, 18, 40, 3, 16, DateTimeKind.Utc).AddTicks(2981),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Moduł komentarzy"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Udostępnianie postów na Facebooku i Twitterze",
                            DueDate = new DateTime(2025, 5, 7, 6, 40, 3, 16, DateTimeKind.Utc).AddTicks(2983),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Integracja z social media"
                        });
                });

            modelBuilder.Entity("ProjectManager.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ProjectManager.Data.Models.ProjectTask", b =>
                {
                    b.HasOne("ProjectManager.Data.Models.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManager.Data.Models.Project", b =>
                {
                    b.Navigation("ProjectTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
