// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjectManager.Data;

#nullable disable

namespace ProjectManager.Data.Migrations
{
    [DbContext(typeof(ProjectManagerDbContext))]
    [Migration("20250204194036_SeedData")]
    partial class SeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProjectManager.Data.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 1, 5, 14, 52, 36, 178, DateTimeKind.Utc).AddTicks(2868),
                            Description = "Aplikacja backendowa w .NET do obsługi kont użytkowników",
                            Name = "System zarządzania użytkownikami"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 1, 13, 7, 40, 36, 178, DateTimeKind.Utc).AddTicks(2877),
                            Description = "Frontendowy panel administracyjny dla systemu zarządzania użytkownikami",
                            Name = "Panel administracyjny Angular"
                        },
                        new
                        {
                            Id = 3,
                            CreatedDate = new DateTime(2024, 12, 26, 0, 28, 36, 178, DateTimeKind.Utc).AddTicks(2880),
                            Description = "Moduł płatności w .NET integrujący różne bramki płatności",
                            Name = "API do obsługi płatności"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 1, 10, 2, 52, 36, 178, DateTimeKind.Utc).AddTicks(2881),
                            Description = "Aplikacja w Angular do analizy sprzedaży i monitorowania zamówień",
                            Name = "Dashboard dla e-commerce"
                        },
                        new
                        {
                            Id = 5,
                            CreatedDate = new DateTime(2025, 2, 2, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2881),
                            Description = "API backendowe dla aplikacji mobilnej do zarządzania zamówieniami",
                            Name = "Aplikacja mobilna dla klientów"
                        },
                        new
                        {
                            Id = 6,
                            CreatedDate = new DateTime(2025, 2, 3, 12, 28, 36, 178, DateTimeKind.Utc).AddTicks(2884),
                            Description = "System zarządzania treścią w .NET dla blogów technologicznych",
                            Name = "CMS dla blogerów"
                        });
                });

            modelBuilder.Entity("ProjectManager.Data.Models.ProjectTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Dodanie funkcji rejestracji z walidacją danych",
                            DueDate = new DateTime(2025, 1, 21, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2914),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Implementacja rejestracji użytkowników"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Funkcja resetowania hasła z kodem weryfikacyjnym na e-mail",
                            DueDate = new DateTime(2025, 1, 15, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2917),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Obsługa resetowania hasła"
                        },
                        new
                        {
                            Id = 3,
                            Description = "System ról i uprawnień dla różnych typów kont",
                            DueDate = new DateTime(2025, 1, 10, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2918),
                            IsCompleted = false,
                            ProjectId = 1,
                            Title = "Dodanie ról użytkowników"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Uwierzytelnianie użytkowników za pomocą tokenów JWT",
                            DueDate = new DateTime(2025, 1, 25, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2919),
                            IsCompleted = true,
                            ProjectId = 1,
                            Title = "Logowanie z wykorzystaniem JWT"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Panel z listą użytkowników i ich statusem",
                            DueDate = new DateTime(2025, 1, 23, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2921),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Stworzenie dashboardu administratora"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Formularz edycji danych użytkownika",
                            DueDate = new DateTime(2025, 1, 17, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2923),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Dodanie edycji profilu użytkownika"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Blokowanie dostępu do sekcji dla nieuprawnionych użytkowników",
                            DueDate = new DateTime(2025, 1, 13, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2924),
                            IsCompleted = false,
                            ProjectId = 2,
                            Title = "Obsługa autoryzacji w panelu"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Dodanie obsługi płatności przez PayU",
                            DueDate = new DateTime(2025, 1, 5, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2925),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Integracja z PayU"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Obsługa powiadomień zwrotnych z bramki płatności",
                            DueDate = new DateTime(2024, 12, 31, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2927),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Implementacja webhooków dla transakcji"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Możliwość zwrotu środków użytkownikowi",
                            DueDate = new DateTime(2024, 12, 26, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2929),
                            IsCompleted = false,
                            ProjectId = 3,
                            Title = "Obsługa zwrotów płatności"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Wykresy i dane dotyczące sprzedaży w sklepie",
                            DueDate = new DateTime(2025, 1, 20, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2931),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Wyświetlanie statystyk sprzedaży"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Podsumowanie najczęściej kupowanych produktów",
                            DueDate = new DateTime(2025, 1, 10, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2932),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Moduł analizy trendów zakupowych"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Funkcja generowania raportów sprzedaży w formacie PDF",
                            DueDate = new DateTime(2025, 1, 15, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2933),
                            IsCompleted = false,
                            ProjectId = 4,
                            Title = "Eksport raportów do PDF"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Obsługa użytkowników w aplikacji mobilnej",
                            DueDate = new DateTime(2025, 2, 2, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2934),
                            IsCompleted = true,
                            ProjectId = 5,
                            Title = "API do logowania i rejestracji"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Funkcja składania zamówień w aplikacji",
                            DueDate = new DateTime(2025, 2, 3, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2936),
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Obsługa zamówień przez API"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Implementacja płatności mobilnych w aplikacji",
                            DueDate = new DateTime(2025, 2, 2, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2937),
                            IsCompleted = false,
                            ProjectId = 5,
                            Title = "Obsługa płatności mobilnych"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Edytor WYSIWYG do tworzenia treści blogowych",
                            DueDate = new DateTime(2025, 2, 4, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2938),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Dodanie edytora tekstu dla blogów"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Obsługa komentarzy pod postami",
                            DueDate = new DateTime(2025, 2, 4, 19, 40, 36, 178, DateTimeKind.Utc).AddTicks(2940),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Moduł komentarzy"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Udostępnianie postów na Facebooku i Twitterze",
                            DueDate = new DateTime(2025, 2, 4, 7, 40, 36, 178, DateTimeKind.Utc).AddTicks(2941),
                            IsCompleted = false,
                            ProjectId = 6,
                            Title = "Integracja z social media"
                        });
                });

            modelBuilder.Entity("ProjectManager.Data.Models.ProjectTask", b =>
                {
                    b.HasOne("ProjectManager.Data.Models.Project", "Project")
                        .WithMany("ProjectTasks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ProjectManager.Data.Models.Project", b =>
                {
                    b.Navigation("ProjectTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
